main: diduhless\parties\Parties
name: Parties
description: A parties plugin for PocketMine-MP servers
website: https://github.com/Diduhless
author: Didah (@Diduhless)
version: 2.0.2-BETA
api: 5.0.0

permissions:
  parties.use:
    default: true
  parties.command:
    default: op
  parties.create:
    default: op
